In [14]:
import numpy as np

def estimate_jacobian(f, x, h,order):
    n = len(x)
    jac = np.zeros((n, n))
    
    for i in range(n):

        x_plus = np.copy(x)
        x_plus[i] += 2 * h
        x_minus = np.copy(x)
        x_minus[i] -= 2 * h
        f_plus = f(x_plus)
        f_minus = f(x_minus)

        for j in range(n):

            x_plusj = np.copy(x)
            x_plusj[j] += h
            x_minusj = np.copy(x)
            x_minusj[j] -= h
            f_plusj = f(x_plusj)
            f_minusj = f(x_minusj)

            if order == 4:
               jac[i, j] = (-f_plusj[i] + 8 * f_plus[i] - 8 * f_minus[i] + f_minusj[i]) / (12 * h)
            
            elif order == 2:
              jac[i, j] = (f_plus[j] - f_minus[j]) / (2 * h)
              

    return jac

def f(x):
    f1 = 6 * x[0] - 2 * np.cos(x[1] * x[2]) - 1
    f2 = 9 * x[1] + np.sqrt((x[0]) ** 2 + np.sin(x[2]) + 1.06) + 0.9
    f3 = 60 * x[2] + 3 * np.exp(-x[0] * x[1]) - 10 * np.pi - 3
    return np.array([f1, f2, f3])

x = np.array([0.5, 0.5, 0.5])
h = 0.01
jacobian_fourth_order = estimate_jacobian(f, x, h,4)
jacobian_second_order = estimate_jacobian(f, x, h,2)

print(jacobian_fourth_order)
print(jacobian_second_order)

[[ 15.          15.95876618  15.95876618]
 [ 23.93770524  22.5         23.94533027]
 [160.19470101 160.19470101 150.        ]]
[[ 12.           0.74748319  -2.33644129]
 [  0.49479967  18.          -2.33644129]
 [  0.49479967   0.65602301 120.        ]]
