In [53]:
import numpy as np
import random

# IMPLEMENTACIÓN DE SOR
def sor(A, b, omega, x0, itmax=1000, tolerancia=1e-9):
    n = len(b)
    x = x0.copy()
    iter_count = 0
    error = tolerancia + 1
    
    while error > tolerancia and iter_count < itmax:
        x_old = x.copy()
        for i in range(n):
            sigma = 0
            for j in range(n):
                if j != i:
                    sigma += A[i][j] * x[j]
            x[i] = (1 - omega) * x_old[i] + (omega / A[i][i]) * (b[i] - sigma)
        error = np.linalg.norm(x - x_old)
        iter_count += 1
    
    return x, iter_count

# DEFINIMOS LOS PÁRAMETROS DE SOR
A = np.array([[3, -1, -1],[-1, 3, 1],[2, 1, 4]])
b = np.array([1, 3, 7])
x0 = np.array([0.,0.,0.])

# COMPROBACIÓN DE QUE EL MÉTODO FUNCIONA PARA ALGUNOS OMEGAS CUALESQUIERA

print(sor(A,b,1.08,x0))
print(sor(A,b,1.16,x0))
print(sor(A,b,1.24,x0))
print(sor(A,b,1.32,x0))

# ENCONTRAR EL VALOR DE OMEGA QUE MINIMIZA EL NUMERO DE ITERACIONES NECESARIAS

omegas = np.linspace(1.01, 1.99, 100)
iteraciones = np.array([])

for omega in omegas:

    x, num_iter = sor(A, b, omega,x0)

    # Almacenar el número de iteraciones necesarias
    iteraciones= np.append(iteraciones,num_iter)

indice_min_iter = np.argmin(iteraciones)
omega_min_iter = omegas[indice_min_iter]
print("El valor de omega que minimiza el número de iteraciones necesarias es " + str(omega_min_iter))






(array([1., 1., 1.]), 24)
(array([1., 1., 1.]), 36)
(array([1., 1., 1.]), 57)
(array([1., 1., 1.]), 113)


<ipython-input-53-0e1e88395edf>:17: RuntimeWarning: overflow encountered in multiply
  sigma += A[i][j] * x[j]
<ipython-input-53-0e1e88395edf>:19: RuntimeWarning: overflow encountered in subtract
  error = np.linalg.norm(x - x_old)
<ipython-input-53-0e1e88395edf>:17: RuntimeWarning: invalid value encountered in double_scalars
  sigma += A[i][j] * x[j]


el valor de omega que minimiza el número de iteraciones necesarias es 1.01
