In [1]:
import sympy as sym
import numpy as np
import matplotlib.pyplot as plt
x = sym.Symbol('x',real=True)
def Laguerre(n):
    return (sym.exp(x)/sym.factorial(n))*(sym.diff(sym.exp(-x)*(x**n),x,n))

In [2]:
def GetNewtonRaphson(f,df,xn,itmax = 100, precision=1e-5):
    
    error = 1
    it = 0
    
    while error > precision and it <= itmax:
        
        try:
            
            xn1 = xn - f(xn)/df(xn)
            
            error = np.abs(f(xn)/df(xn))
            
            #print(error)
            
        except ZeroDivisionError:
            
            print('Division por cero')
            
        it += 1
        xn = xn1
    
    if it == itmax:
        False
    else:
        return xn
    
def GetAllRoots(x,tolerancia=8):
    
    Roots = np.array([])
    
    for i in x:
        
        root = GetNewtonRaphson(func,funcd,i)
        
        if root != False:
            
            croot = np.round(root, tolerancia)
            
            if croot not in Roots:
                Roots = np.append(Roots,croot)
                
    Roots.sort()
        
    return Roots

In [3]:
n = 20
for i in range(n):
    x = sym.Symbol('x',real=True)
    f = Laguerre(i+1)
    df = sym.diff(f,x)
    func = sym.lambdify([x],f,'numpy')
    funcd = sym.lambdify([x],df,'numpy')
    y = np.linspace(-10,10,1000)
    roots = GetAllRoots(y)
    print("Las raíces para: Laguerre "+str(i+1)+"son: ")
    print(roots)

Las raíces para: Laguerre 1son: 
[1.]
Las raíces para: Laguerre 2son: 
[0.58578644 3.41421356]
Las raíces para: Laguerre 3son: 
[0.41577456 2.29428036 6.28994508]
Las raíces para: Laguerre 4son: 
[0.32254769 1.7457611  4.5366203  9.39507091]
Las raíces para: Laguerre 5son: 
[ 0.26356032  1.41340306  3.59642577  7.08581001 12.64080084]
Las raíces para: Laguerre 6son: 
[ 0.2228466   1.1889321   2.99273633  5.77514357  9.83746742 15.98287398]
Las raíces para: Laguerre 7son: 
[ 0.19304368  1.0266649   2.56787674  4.90035308  8.18215344 12.73418029
 19.39572786]
Las raíces para: Laguerre 8son: 
[ 0.17027963  0.90370178  2.25108663  4.26670017  7.0459054  10.75851601
 15.74067864 22.86313174]
Las raíces para: Laguerre 9son: 
[ 0.15232223  0.80722002  2.00513516  3.78347397  6.20495678  9.37298525
 13.46623691 18.83359779 26.37407189]
Las raíces para: Laguerre 10son: 
[ 0.13779347  0.72945455  1.8083429   3.4014337   5.55249614  8.33015275
 11.84378584 16.27925783 21.99658581 29.92069701]
Las

-x**7/5040 + 7*x**6/720 - 7*x**5/40 + 35*x**4/24 - 35*x**3/6 + 21*x**2/2 - 7*x + 1